### ISSUE TITLE
ERRORS.RUNTIME_ROWSIZE_MISMATCH on 3.8

### ISSUE THREAD

**Issue by frepe698** [brather1ng/RePoE#12]
Hi, I am getting the following error when running on the 3.8 content file. I see you successfully have done it though so I wonder why this could be. Any clues? 

```
Traceback (most recent call last):
  File "repoe.py", line 2, in <module>
    RePoE.main('data/')
  File "C:\Users\fredr\dev\pathofcrafting\RePoE\RePoE\__init__.py", line 62, in main
    translation_file_cache=tfc, ot_file_cache=otfc)
  File "C:\Users\fredr\dev\pathofcrafting\RePoE\RePoE\crafting_bench_options.py", line 8, in write_crafting_bench_options
    for row in relational_reader['CraftingBenchOptions.dat']:
  File "c:\users\fredr\dev\pathofcrafting\pypoe\PyPoE\poe\file\dat.py", line 976, in __getitem__
    return self.get_file(item).reader
  File "c:\users\fredr\dev\pathofcrafting\pypoe\PyPoE\poe\file\dat.py", line 1058, in get_file
    df = self._create_instance(file_name)
  File "c:\users\fredr\dev\pathofcrafting\pypoe\PyPoE\poe\file\shared\cache.py", line 214, in _create_instance
    f.read(**self._get_read_args(file_name=file_name, *args, **kwargs))
  File "c:\users\fredr\dev\pathofcrafting\pypoe\PyPoE\poe\file\shared\__init__.py", line 192, in read
    return self.get_read_buffer(file_path_or_raw, self._read, *args, **kwargs)
  File "c:\users\fredr\dev\pathofcrafting\pypoe\PyPoE\poe\file\shared\__init__.py", line 151, in get_read_buffer
    return function(*args, buffer=file_path_or_raw, **kwargs)
  File "c:\users\fredr\dev\pathofcrafting\pypoe\PyPoE\poe\file\dat.py", line 917, in _read
    self.reader.read(buffer.read())
  File "c:\users\fredr\dev\pathofcrafting\pypoe\PyPoE\poe\file\dat.py", line 810, in read
    'cast_size': self.table_record_length
PyPoE.poe.file.specification.errors.SpecificationError: <ERRORS.RUNTIME_ROWSIZE_MISMATCH: 3002>: "CraftingBenchOptions.dat": Specification row size 150 vs real size 158
```

**Comment by brather1ng** [comment]
I just added/removed fields in my PyPoE clone's spec until it worked. But now PyPoE's spec was updated properly anyway.
